language: node_js
node_js:
  - "node"

services:
  - mongodb

before_install:
  - stty cols 80

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
  - sleep 15
  - mongo TestFairBnB --eval 'db.createUser({user:"travis"wd:"test",roles:["readWrite"]});'

after_success:
  - npm run coveralls

dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
